### ISSUE TITLE
Cannot install v2.0.0 in CI

### ISSUE THREAD

**Issue by acalvo** [vale-cli/vale#174]
I'm getting started with Vale. I tried to install the latest version (v2.0.0) in my CI following the instructions given in <https://errata-ai.gitbook.io/vale/getting-started/installation#using-vale-with-a-continuous-integration-ci-service> but it failed. Installing v1.7.1 went OK, though.

After debugging `vale.sh` to see what was going on, it seems that the problem is that it tries to download it from this URL:

> https://github.com/errata-ai/vale/releases/download/v2.0.0/vale_2.0.0_Linux_64-bit.tar.gz

...and it doesn't exist. The existing URL is:

> [https://github.com/errata-ai/vale/releases/download/v2.0.0/vale_**v**2.0.0_Linux_64-bit.tar.gz](https://github.com/errata-ai/vale/releases/download/v2.0.0/vale_v2.0.0_Linux_64-bit.tar.gz)

Note the **v** before the second `2.0.0`.

It works for v1.7.1 because it seeks this URL and it does exist:

> https://github.com/errata-ai/vale/releases/download/v1.7.1/vale_1.7.1_Linux_64-bit.tar.gz

So, could you upload the 2.0.0 version without the **v** so that the script works? Thanks! 😄

**Comment by jdkato** [comment]
This should be fixed.

**Comment by acalvo** [comment]
@jdkato I'm still unable to install v2.0.0 following https://errata-ai.gitbook.io/vale/getting-started/installation#using-vale-with-a-continuous-integration-ci-service . After debugging `vale.sh` again, it seems that this file is missing now:

> https://github.com/ValeLint/vale/releases/download/v2.0.0/vale_2.0.0_checksums.txt

Any chance you can upload it? Thanks!

**Comment by jdkato** [comment]
Thanks for investigating this.

I've verified this is indeed working now and I've added it as a step in Travis CI to avoid this in the future.

**Comment by acalvo** [comment]
Yes! Now it works great. Thanks! 😊
